server {
    listen 80;
    listen [::]:80;
    server_name moa.chocolily.dev moa.moria-luluka.com moa.morialuluka.com moa.xn--o39a013c.tv;
    location ^~ /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 308 https://$host$request_uri; }
}
